MPICC = mpicc
MPICPP = mpicxx
CFLAGS = -Wall -W -Wno-unused -Werror -g

OBJECTS = ../debug.o
TESTS = sendrecv probe tsetup fwrite

DALOBJECTS = $(OBJECTS) ../dal.o
DALTESTS = daltest dalsendrecv dalalltoall dalscatter dalalltoallv dalscatterv dalgatherv

all: tests

tests: $(TESTS) $(DALTESTS)

$(TESTS): $(OBJECTS)
	@echo "Compiling $@..."
	$(MPICC) $(CFLAGS) $@.c $(OBJECTS) -o $@

$(DALTESTS): $(OBJECTS) $(DALOBJECTS)
	@echo "Compiling $@..."
	$(MPICC) $(CFLAGS) $@.c $(DALOBJECTS) -o $@

clean:
	rm -f *~ *.o $(TESTS) $(DALTESTS)
